# Generated by Django 2.2.10 on 2020-08-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='packaging',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='rider_on_the_way',
            field=models.BooleanField(default=False),
        ),
    ]
